ignore:
  - "examples"
  - "stakeholder_test"
  - "etc"
  - "src/astrohack/scripts/verification"
  - "src/astrohack/config"
  - "src/astrohack/data"
  - "tests"
  - "release_script.py"
  - "benchmarks"
