[project]
name = "astrohack"
version = "1.0.2"
description = "Holography Antenna Commissioning Kit"
readme = "README.md"
requires-python = ">= 3.11, < 3.14"
dependencies = [ "astropy", "dask", "shapely", "distributed", "toolviper", "ipywidgets", "matplotlib", "numba>=0.57.0", "numpy<=2.2", "prettytable", "pycryptodome", "pytest", "pytest-cov", "pytest-html", "scikit_image", "scikit-learn", "scipy", "rich", "xarray", "zarr<3.0.0", "bokeh", "pillow", "jupyterlab", "casacoretables>=0.0.3",]
[[project.authors]]
name = "Joshua Hoskins"
email = "jhoskins@nrao.edu"

[[project.authors]]
name = "Victor de Souza Magalhaes"
email = "vdesouza@nrao.edu"

[[project.authors]]
name = "Jan-Willem Steeb"
email = "jsteeb@nrao.edu"

[project.license]
file = "LICENSE.txt"

[project.optional-dependencies]
docs = ["pandoc", "sphinx-autosummary-accessors", "nbsphinx", "sphinx_rtd_theme", "recommonmark", "sphinx-autoapi", "ipython"]

[project.scripts]
beamcut-reduction-pipeline = "astrohack.scripts.beamcuts.beamcut_reduction_pipeline:main"
beamcut-calibration = "astrohack.scripts.beamcuts.beamcut_CASA_calibration:main"
baseline-reduction-pipeline = "astrohack.scripts.baseline.baseline_CASA_pipeline:main"