# Run MacOS tests using template in ToolVIPER
name: MacOS Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  call-testing-linux:
    uses: nrao/gh-actions-templates-public/.github/workflows/python-testing-macos-template.yml@main
