# Run Linux tests using template in ToolVIPER
name: Linux Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  call-testing-linux:
    uses: nrao/gh-actions-templates-public/.github/workflows/python-testing-linux-template.yml@main
    with:
      cov_project: "astrohack"
      test-path: "tests/"
    secrets: inherit
