# .github/workflows/python-testing-linux.yml
name: ipynb Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
 
  call-testing-linux:
    uses: nrao/gh-actions-templates-public/.github/workflows/run-ipynb-template.yml@main
    secrets: inherit