# .github/workflows/python-testing-linux.yml
name: ipynb Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:

  trace-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: honeycombio/gha-buildevents@v2
        with:
          secrets: inherit
          # Required: a Honeycomb API key - needed to send traces.
          apikey: ${{ secrets.BUILDEVENT_APIKEY }}
          
          # Required: the Honeycomb dataset to send traces to.
          dataset: buildevents

          # Optional: status, this will be used in the post section and sent
          # as status of the trace. Set on the final job of a workflow to signal for the trace to # end
          # job-status has been deprecated
          status: ${{ job.status }}

      - name: "Honeycomb: Start Linux tests"
        run: |
          # Each Job MUST include unique STEP IDs to ensure each job's spans are properly organized together.
          # Export environment variables used by the finish step.
          echo "STEP_ID=linux-tests" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV

      - name: "Linux tests"
        uses:  nrao/gh-actions-templates-public/.github/workflows/run-ipynb-template.yml@main

      - name: "Honeycomb: Finish Linux tests"
        run: buildevents step $TRACE_ID $STEP_ID $STEP_START $STEP_ID
